# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 11:25
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import organizations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_external_ids_for_pandiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationowner',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationowner',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
