# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20160921_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this is a subgroup, select its parent here', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_pandi_club',
            field=models.BooleanField(db_index=True, default=False, help_text='This group represents a club of P&I insurers'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the organization', max_length=200),
        ),
    ]
