# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20161003_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='signup_message',
            field=models.TextField(blank=True, default=b'You have been added to {{ organization.name }}.\nClick {{ link }} for the group profile.', help_text="Message sent when user is added to group. Use {{ organization.name }} for the group name, {{ user.get_full_name }} for the user's name, and {{ link }} for a link to the group.", null=True),
        ),
    ]
