# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20161005_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='send_signup_message',
            field=models.BooleanField(default=False),
        ),
    ]
